
```{r}
library(rehh)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(data.table)
library(DBI)
library(RSQLite)
library(scales)
library(lubridate)
library(data.table)
```

```{r}
filename <- file.choose()
covid_2<- readRDS(filename)
## 少的那个
covid_2 <- covid_2 %>%  filter(grepl(pattern = 'Spike', AASubstitutions))
covid_2 <- covid_2[!is.na(covid_2$date),]
# covid_2 <- df[complete.cases(covid),]
# colnames(covid_2)[names(covid_2) == 'GC-Content'] <- "GCContent"
# saveRDS(covid_2, file = filename)
```

```{r}
covid_2$VarShort[is.na(covid_2$VarShort)] <- "Origin"
covid_ns <- covid_2 %>% group_by(pangolin_lineage) %>% arrange(date) %>% mutate(no = row_number(date)) ######### "no" here used to delete 5% data, later will be factor for >1 or not

covid_ns$pangolin_lineage[which(covid_ns$VarShort == "VOC Delta GK")] <- "Delta"


# %>% filter(pangolin_lineage == c("BA.1","BA.2","BA.2.12.1","BA.4","BA.5","BF.7","BQ.1.1"))
covid_ns <- covid_ns[-which(covid_ns$no < 5),]

# covid_2 <- covid_2[order(covid_2$pangolin_lineage,covid_2$date)]

covid_n_1 <- aggregate(covid_ns$count_N, by=list( covid_ns$pangolin_lineage,covid_ns$VarShort,covid_ns$date),mean)

# covid_ns <- data.frame(covid_ns,covid_ns_1)
names(covid_n_1) <- c("pangolin_lineage", "VarShort", "date", "count_N")

covid_n_1 <- covid_n_1[order(covid_n_1$pangolin_lineage,covid_n_1$date),]

# ggplot(covid_n_1, aes(x = date, y = count_N, color = pangolin_lineage)) +
#   geom_point() +
#   labs(title = "Count_N by lineage")

############### N ##############
############### S ##############

covid_s_1 <- aggregate(covid_ns$count_S, by=list(covid_ns$pangolin_lineage,covid_ns$VarShort,covid_ns$date),mean)
# covid_ns <- data.frame(covid_ns,covid_ns_1)
names(covid_s_1) <- c("pangolin_lineage", "VarShort", "date", "count_S")

covid_s_1 <- covid_s_1[order(covid_s_1$pangolin_lineage,covid_s_1$date),]

ggplot(covid_s_1, aes(x = date, y = count_S, color = VarShort)) +
  geom_point() +
  labs(title = "Count_S by lineage")

delta_N <- diff(covid_n_1$count_N)
delta_N <- c(0,delta_N)
covid_n_1$delta_N <- delta_N


delta_S <- diff(covid_s_1$count_S)
delta_S <- c(0,delta_S)
covid_s_1$delta_S <- delta_S

dnds <- data.frame(covid_s_1$date, covid_s_1$pangolin_lineage,delta_N/delta_S)
names(dnds) <- c("date","pangolin_lineage","dnds")


dnds <- dnds[!is.infinite(dnds$dnds),]
dnds <- dnds[!is.na(dnds$dnds),]

# ggplot(dnds, aes(x = date, y = dnds)) +
#   geom_point() +
#   ylim(-100,100) +
#   labs(title = "dNdS")


delta_N <- diff(covid_ns$count_N)
delta_N <- c(0,delta_N)
covid_ns$delta_N <- delta_N


delta_S <- diff(covid_ns$count_S)
delta_S <- c(0,delta_S)
covid_ns$delta_S <- delta_S

covid_ns$dnds <- delta_N/delta_S

covid_ns <- covid_ns[!is.infinite(covid_ns$dnds),]
covid_ns <- covid_ns[!is.na(covid_ns$dnds),]
covid_ns <- covid_ns[!is.na(covid_ns$VarShort),]

# ggplot(covid_ns, aes(x = date, y = dnds, col = pangolin_lineage)) +
#   geom_point()

############ Linear Regression on N
# lineage_name = c("BA.1","BA.2","BA.2.1","BA.2.75","BA.4","BA.5","BA.5.2.1","BF.7","BQ.1","BQ.1.1","BN.1","XBB")


var_name = c("VOC Omicron GRA", "VOC Delta GK")
# var_name = c("VOC Delta GK")

covid_ns_2 <- covid_ns[covid_ns$VarShort == var_name,]

fitted_N =  covid_ns_2 %>% group_by(pangolin_lineage) %>% do(model = lm(count_N ~ date, data = .))
# plot(fitted_models$model)
# fitted_N$model

######### Linear Regression on S
# covid_s_2 <- covid_ns[covid_ns$VarShort == var_name,]
fitted_S =  covid_ns_2 %>% group_by(pangolin_lineage) %>% do(model = lm(count_S ~ date, data = .))
# plot(fitted_models$model)
# fitted_S$model
# fitted_S <- lm(count_S ~ date,covid_s_2, subset = (grp == "pango"))
# fitted_S

a <- list()
for (i in 1:nrow(fitted_N)) {
  a[i] <- fitted_N[[2]][[i]][["coefficients"]][2] / fitted_S[[2]][[i]][["coefficients"]][2]
}  ### bootstrap of dnds
# dnds <- data.frame(matrix(nrow=0,ncol=2))
dnds <- data.frame(fitted_N$pangolin_lineage)
names(dnds) <- c("pangolin_lineage")
dnds$dNdS <- a

# dnds <- dnds[!is.infinite(dnds$dNdS),]
dnds <- dnds[!is.na(dnds$dNdS),]


# dnds <- dnds[!is.na(dnds$dNdS),]

dnds[dnds$pangolin_lineage == "BA.2",]$dNdS
####### Haven't consider p<0.01



# ggplot(data = dnds, aes(x = pangolin_lineage, y = dNdS)) +
#   geom_bar(stat = 'identity')

lineage_name = c("Delta","BA.1","BA.2","BA.2.12.1","BA.2.75","BA.4","BA.5","BA.5.2.1","BF.7","BQ.1","BQ.1.1","BN.1","XBB")
# covid_specific <- covid_2 %>% filter(pangolin_lineage == lineage_name)
# covid_4 <- dnds[dnds$pangolin_lineage == lineage_name,]
dnds_multiple_dnds <- list()
dnds_multiple_lineage <- list()
for (i in 1:length(lineage_name))
{
  dnds_multiple_dnds[i] <- dnds[dnds$pangolin_lineage == lineage_name[i],]$dNdS
  dnds_multiple_lineage[i] <- dnds[dnds$pangolin_lineage == lineage_name[i],]$pangolin_lineage
}
dnds_multiple <- data.frame(dnds_multiple_lineage,dnds_multiple_dnds)

# dnds_multiple <- data.frame(dnds_multiple_lineage)
# names(dnds_multiple) <- c("pangolin_lineage")
# dnds$dNdS <- dnds_multiple_dnds

dnds_multiple <- cbind(dnds_multiple_lineage,dnds_multiple_dnds)
dnds_multiple <- as.data.frame(dnds_multiple)
names(dnds_multiple) <- c("pangolin_lineage","dNdS")
dnds_multiple$dNdS <- as.numeric(dnds_multiple$dNdS)
dnds_multiple$pangolin_lineage <- as.factor(lineage_name)

dnds_multiple$col<- ifelse(dnds_multiple$dNdS >= 1, 1, 0)
dnds_multiple$col<-as.factor(dnds_multiple$col)
dnds_multiple <- dnds_multiple %>%
  mutate(pangolin_lineage = factor(pangolin_lineage, levels = lineage_name))

ggplot(dnds_multiple, mapping = aes(x = dnds_multiple$pangolin_lineage, y = dnds_multiple$dNdS, col = dnds_multiple$col, fill = dnds_multiple$col, levels = lineage_name)) +
  geom_bar(position="dodge",stat="identity") +
  labs(title = "dNdS_new in different Concern Lineages") +
  ylim(0,7)

# dnds[dnds$pangolin_lineage == "XBB",]$dNdS

# lineage_name = lineage_name
# lineage_name = c("BQ.1")
# covid_specific <- covid_2 %>% filter(pangolin_lineage == lineage_name)

covid_specific <- covid_ns_2[covid_ns_2$pangolin_lineage == lineage_name,]
covid_specific <- covid_specific[!is.na(covid_specific$delta_N),]

dnds[dnds$pangolin_lineage == lineage_name,]$dNdS


ggplot(data = covid_specific, mapping = aes(x = date, y = count_N, col = covid_specific$pangolin_lineage)) +
  # geom_point() +
  xlab('date') +
  labs(title = "delta_N(slope)") +
  geom_smooth(method = lm)

ggplot(data = covid_specific, mapping = aes(x = date, y = count_N, col = covid_specific$pangolin_lineage)) +
  geom_point() +
  xlab('date') +
  labs(title = "count_N")

ggplot(data = covid_specific, mapping = aes(x = date, y = count_S, col = covid_specific$pangolin_lineage)) +
  # geom_point() +
  xlab('date') +
  labs(title = "delta_S(slope)") +
  geom_smooth(method = lm)

ggplot(data = covid_specific, mapping = aes(x = date, y = count_S, col = covid_specific$pangolin_lineage)) +
  geom_point() +
  xlab('date') +
  labs(title = "count_S")

covid_specific_2 <- covid_specific[covid_specific$pangolin_lineage == "BA.2",]
ggplot(data = covid_specific_2, mapping = aes(x = date, y = count_N)) +
  geom_point() +
  xlab('date') +
  labs(title = "count_N BA.2") +
  geom_smooth(method = lm)

covid_specific_2 <- covid_specific[covid_specific$pangolin_lineage == "BA.2",]
ggplot(data = covid_specific_2, mapping = aes(x = date, y = count_S)) +
  geom_point() +
  xlab('date') +
  labs(title = "count_S BA.2") +
  geom_smooth(method = lm)
```


# Week 14
bootstrap of count_N and count_S   
pd_N pd_S   
```{r}
# library(boot)
set.seed(1234)
lineage_name <- c("BA.5")
covid_specific_1 <- covid_specific[covid_specific$pangolin_lineage == lineage_name,]
covid_specific_1 <- covid_specific_1[,c("date","count_N", "count_S")]
pd_NS   <- covid_specific_1
slope_NS <- 0
# pd$b <- 0
for (i in 1:500) {
  j    <- sample(1:nrow(covid_specific_1), replace = TRUE)
  nd   <- covid_specific_1[j,]
  fitted_N <- lm(data = nd, count_N ~ date)
  fitted_S <- lm(data = nd, count_S ~ date)
  slope <- fitted_N[["coefficients"]][2] / fitted_S[["coefficients"]][2]
  # nd$b <- i
  slope_NS   <- rbind(slope_NS, slope)
  
  if(i%%100==0) {   # Progress tracker
    cat(i, "\n")       
    flush.console()
  }
  
}
slope_NS <- data.frame(slope_NS)
slope_NS$cnt <- round(slope_NS$date,2)
slope_NS <- slope_NS[slope_NS$cnt > -5,]
slope_NS <- slope_NS[slope_NS$cnt < 5,]
# hist(slope_NS)
calculated <- dnds[dnds$pangolin_lineage == lineage_name,]$dNdS
calculated <- as.data.frame(calculated)
colnames(calculated) <- c("dnds")

## dnds[dnds$pangolin_lineage == lineage_name]$dNdS,]
sumstatz <- data.frame(whichstat = c("mean",
                                     "calculated",
                                     "median",
                                     "low CI",
                                     "upp CI"),
                       value     = c(mean(slope_NS$date),
                                     calculated$dnds,
                                     median(slope_NS$date),
                                     mean(slope_NS$date) - 1.96*sd(slope_NS$date),
                                     mean(slope_NS$date) + 1.96*sd(slope_NS$date) # 95% CI
                                    )
                       )

ggplot(slope_NS, aes(x = cnt)) +
  geom_histogram(bins = 30, fill="#69b3a2", color="black", alpha=0.9 , position = "identity") +
  xlab("dNdS") +
  geom_vline(data=sumstatz,aes(xintercept = value,
                               linetype = whichstat,
                               col = whichstat),size=1) +
  theme(
    axis.text.y=element_text(size=12),
          axis.text.x=element_text(size=12),
          axis.line = element_line(size=0.6),
          axis.ticks = element_line(size=0.6),
          axis.ticks.length = unit(2,'mm'),
          axis.title = element_text(colour = "black",size=15),
          panel.background = element_blank()
  ) +
  labs(title = "dnds BA.2 boots = 500") 

# mean(slope_NS$date)

# t.test(slope_NS$date,conf=0.95)
sumstatz
```

```{r}
count <- table(slope_NS$cnt)
count <- data.frame(count)
count$Var1 <- as.numeric(as.character(count$Var1))
count <- count[count$Var1 > -3,]
count <- count[count$Var1 < 3,]

```

