---
title: "Covid_3"
author: "zly"
date: "2022-10-18"
output: html_document
---

```{r}
library(rehh)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(data.table)
library(DBI)
library(RSQLite)
library(scales)
library(data.table)
```

```{r}
filename <- file.choose()
covid <- readRDS(filename)
## 多的那个
```


```{r}
filename <- file.choose()
covid_2<- readRDS(filename)
## 少的那个
covid_2 <- covid_2 %>%  filter(grepl(pattern = 'Spike', AASubstitutions))
# covid_2 <- df[complete.cases(covid),]
# colnames(covid_2)[names(covid_2) == 'GC-Content'] <- "GCContent"
# saveRDS(covid_2, file = filename)
```

```{r}

covid3 <- covid %>%
  filter(effect == "missense_variant")
covid_snp_sub <- covid_2[,c("id","date","VarShort","pangolin_lineage")] 
# covid_ann_sub <- covid3[,c("id","position","aa_change")]
covid_ann_sub <- covid[,c("id","position","aa_change","impact")]
covid3 <- merge(covid_ann_sub,covid_snp_sub,by = "id")
# covid3 <- covid3[!duplicated(covid3),]

# covid5 <- covid3 %>%
#   filter(aa_change == "K356T")
# # covid5 <- covid5[covid5$pangolin_lineage == c("BA.1","BA.2","BA.2.12.1","BA.5"),]
# # covid5 <- covid5[covid5$VarShort == c("VOC Omicron GRA", "VOC Alpha GRY", "VOC Delta GK", "VOC Beta GH"),]
# ggplot(data = covid5, mapping = aes(x = date, col = pangolin_lineage)) +
#   geom_histogram() +
#   labs(title = "K356T")
```

## covid3 file just read from here
```{r}
# saveRDS(covid3, file = "mutations_covid3.rds")
# filename <- file.choose()
# covid3 <- readRDS(filename)
```

Finding relative growth advantage of BA.5 to BA.2
```{r}
# covid3_ba5 <- covid3[covid3$pangolin_lineage == c("BA.4"),]

covid3_ba5 <- covid3[covid3$VarShort == c("VOC Delta GK"),]
covid3_ba2 <- covid3[covid3$pangolin_lineage == c("BA.2.12"),]
covid3_delta <- covid3[covid3$VarShort == c("VOC Delta GK"),]
```


```{r}
# covid3_ba5 <- covid3
# covid3_ba5 <- covid3[covid3$pangolin_lineage == c("BQ.1.1"),]
# covid3_ba5 <- covid3[covid3$VarShort == c("VOC Omicron GRA"),]
covid3_ba5 <- covid3[covid3$VarShort == c("VOC Delta GK"),]

covid3_ba5 <- covid3_ba5 %>% filter(aa_change == "P309L") 
# %>% filter(year(date) >= 2021)
tb1 <- table(covid3_ba5$date)
tb2 <- table(covid_2$date)
tb1 <- data.frame(tb1)
tb2 <- data.frame(tb2)
names(tb1) <- c("date","num1")
names(tb2) <- c("date","num2")
covid4_ba5 <- merge(tb1,tb2,by = "date")
covid4_ba5["Freq"] <- covid4_ba5$num1 / covid4_ba5$num2
M1 <- mean(covid4_ba5$Freq)
M1
library(lubridate)
# date <- as.Date(covid4_ba5$date, "%Y/%m/%d")
# covid4_ba5 <- mutate(covid4_ba5, date)
covid4_ba5$date = ymd(covid4_ba5$date)
Sys.setlocale("LC_TIME", "English") 
ggplot(data = covid4_ba5, mapping = aes(x = date, y = Freq)) +
  geom_point() +
  labs(title = "P309L,Delta") +
  scale_x_date(limits = c()) +
  scale_y_continuous(limits=c(0,1),oob=rescale_none) +
  geom_hline(aes(yintercept=M1))
# 
# covid3_ba2 %>% filter(aa_change == "S704L")
# tb1 <- table(covid3_ba2$date)
# tb2 <- table(covid_2$date)
# tb1 <- data.frame(tb1)
# tb2 <- data.frame(tb2)
# names(tb1) <- c("date","num1")
# names(tb2) <- c("date","num2")
# covid4_ba2 <- merge(tb1,tb2,by = "date")
# covid4_ba2["Freq"] <- covid4_ba2$num1 / covid4_ba2$num2
# ggplot(data = covid4_ba2, mapping = aes(x = date, y = Freq)) +
#   geom_point() +
#   labs(title = "S704L, BA.2.12") +
#   scale_x_discrete(" ")

```


Compare BA1 and BA2
```{r}
covid3_ba5 <- covid3[covid3$pangolin_lineage == c("BA.1"),]
covid3_ba2 <- covid3[covid3$pangolin_lineage == c("BA.2"),]

covid3_ba5 %>% filter(aa_change == "N969K")
tb1 <- table(covid3_ba5$date)
tb2 <- table(covid_2$date)
tb1 <- data.frame(tb1)
tb2 <- data.frame(tb2)
names(tb1) <- c("date","num1")
names(tb2) <- c("date","num2")
covid4_ba5 <- merge(tb1,tb2,by = "date")
covid4_ba5["Freq"] <- covid4_ba5$num1 / covid4_ba5$num2
ggplot(data = covid4_ba5, mapping = aes(x = date, y = Freq)) +
  geom_point() +
  labs(title = "N969K, BA.1") +
  scale_x_discrete(" ")

covid3_ba2 %>% filter(aa_change == "N969K")
tb1 <- table(covid3_ba2$date)
tb2 <- table(covid_2$date)
tb1 <- data.frame(tb1)
tb2 <- data.frame(tb2)
names(tb1) <- c("date","num1")
names(tb2) <- c("date","num2")
covid4_ba2 <- merge(tb1,tb2,by = "date")
covid4_ba2["Freq"] <- covid4_ba2$num1 / covid4_ba2$num2
ggplot(data = covid4_ba2, mapping = aes(x = date, y = Freq)) +
  geom_point() +
  labs(title = "N969K, BA.2") +
  scale_x_discrete(" ")

```

## Week 8
1. Checking S704L and L452 of Omicron and Delta   
```{r}
covid3_ba5 <- covid3[covid3$pangolin_lineage == c("BA.5"),]
# covid3_ba2 <- covid3[covid3$pangolin_lineage == c("BA.2.12"),]
covid3_delta <- covid3[covid3$VarShort == c("VOC Delta GK"),]

# covid3_ba5 <- covid3_ba5 %>% filter(aa_change == "R346Q")
# tb1 <- table(covid3_ba5$date)
# tb2 <- table(covid_2$date)
# tb1 <- data.frame(tb1)
# tb2 <- data.frame(tb2)
# names(tb1) <- c("date","num1")
# names(tb2) <- c("date","num2")
# covid4_ba5 <- merge(tb1,tb2,by = "date")
# covid4_ba5["Freq"] <- covid4_ba5$num1 / covid4_ba5$num2
# ggplot(data = covid4_ba5, mapping = aes(x = date, y = Freq)) +
#   geom_point() +
#   labs(title = "R346Q, BA.5") +
#   scale_x_discrete(" ")

covid3_delta <- covid3_delta %>% filter(aa_change == "S704L")
tb1 <- table(covid3_delta$date)
tb2 <- table(covid_2$date)
tb1 <- data.frame(tb1)
tb2 <- data.frame(tb2)
names(tb1) <- c("date","num1")
names(tb2) <- c("date","num2")
covid4_delta <- merge(tb1,tb2,by = "date")
covid4_delta["Freq"] <- covid4_delta$num1 / covid4_delta$num2
ggplot(data = covid4_delta, mapping = aes(x = date, y = Freq)) +
  geom_point() +
  labs(title = "S704L, Delta") +
  scale_x_discrete(" ")
```

```{r}
covid3_ba5 <- covid3[covid3$pangolin_lineage == c("Delta"),]
covid3_ba5 <- covid3_ba5 %>% filter(aa_change == "S704L")
tb1 <- table(covid3_ba5$date)
tb2 <- table(covid_2$date)
tb1 <- data.frame(tb1)
tb2 <- data.frame(tb2)
names(tb1) <- c("date","num1")
names(tb2) <- c("date","num2")
covid4_ba5 <- merge(tb1,tb2,by = "date")
covid4_ba5["Freq"] <- covid4_ba5$num1 / covid4_ba5$num2
ggplot(data = covid4_ba5, mapping = aes(x = date, y = Freq)) +
  geom_point() +
  labs(title = "S704L, BA.1") +
  scale_x_discrete(" ")
```

2. BF.7 and BA.5
```{r}
covid3_ba5 <- covid3[covid3$pangolin_lineage == c("BF.7"),]
covid3_ba2 <- covid3[covid3$pangolin_lineage == c("BF.7"),]
```

```{r}
covid3_ba5 <- covid3_ba5 %>% filter(aa_change == "L452R")
tb1 <- table(covid3_ba5$date)
tb2 <- table(covid_2$date)
tb1 <- data.frame(tb1)
tb2 <- data.frame(tb2)
names(tb1) <- c("date","num1")
names(tb2) <- c("date","num2")
covid4_ba5 <- merge(tb1,tb2,by = "date")
covid4_ba5["Freq"] <- covid4_ba5$num1 / covid4_ba5$num2
ggplot(data = covid4_ba5, mapping = aes(x = date, y = Freq)) +
  geom_point() +
  labs(title = "L452R, BA.5") +
  scale_x_discrete(" ")
```

3. Others
```{r}
covid3_ba5 <- covid3[covid3$pangolin_lineage == c("BF.7"),]
# covid3_ba2 <- covid3[covid3$pangolin_lineage == c("BF.5"),]

covid3_ba5 <- covid3_ba5 %>% filter(aa_change == "P4715L")
tb1 <- table(covid3_ba5$date)
tb2 <- table(covid_2$date)
tb1 <- data.frame(tb1)
tb2 <- data.frame(tb2)
names(tb1) <- c("date","num1")
names(tb2) <- c("date","num2")
covid4_ba5 <- merge(tb1,tb2,by = "date")
covid4_ba5["Freq"] <- covid4_ba5$num1 / covid4_ba5$num2
ggplot(data = covid4_ba5, mapping = aes(x = date, y = Freq)) +
  geom_point() +
  labs(title = "P4715L, BA.5") +
  scale_x_discrete(" ")
```
```{r}
covid3_delta <- covid3[covid3$VarShort == c("VOC Delta GK"),]
covid3_delta <- covid3_delta %>% filter(aa_change == "D614G")
tb1 <- table(covid3_delta$date)
tb2 <- table(covid_2$date)
tb1 <- data.frame(tb1)
tb2 <- data.frame(tb2)
names(tb1) <- c("date","num1")
names(tb2) <- c("date","num2")
covid4_delta <- merge(tb1,tb2,by = "date")
covid4_delta["Freq"] <- covid4_delta$num1 / covid4_delta$num2
ggplot(data = covid4_delta, mapping = aes(x = date, y = Freq)) +
  geom_point() +
  labs(title = "D614G, Delta") +
  scale_x_discrete(" ")
```

4. BA.5.2.1 -> BF.7
```{r}
covid3_ba5 %>% count(aa_change) %>% arrange(-n)
```

```{r}
covid3_ba5 <- covid3[covid3$pangolin_lineage == c("BF.7"),]
# covid3_ba2 <- covid3[covid3$pangolin_lineage == c("BF.5"),]

covid3_ba5 <- covid3_ba5 %>% filter(aa_change == "D614G")
tb1 <- table(covid3_ba5$date)
tb2 <- table(covid_2$date)
tb1 <- data.frame(tb1)
tb2 <- data.frame(tb2)
names(tb1) <- c("date","num1")
names(tb2) <- c("date","num2")
covid4_ba5 <- merge(tb1,tb2,by = "date")
covid4_ba5["Freq"] <- covid4_ba5$num1 / covid4_ba5$num2
ggplot(data = covid4_ba5, mapping = aes(x = date, y = Freq)) +
  geom_point() +
  labs(title = "D614G, BA.5.2.1") +
  scale_x_discrete(" ")
```
5. Num of mutations in Omicron variants
```{r}
covid3_ba5 <- covid3[covid3$pangolin_lineage == c("BA.5.2.1"),]
tb1 <- table(covid3_ba5$date)
tb2 <- table(covid_2$date)
tb1 <- data.frame(tb1)
tb2 <- data.frame(tb2)
names(tb1) <- c("date","num1")
names(tb2) <- c("date","num2")
Num_mutation <- merge(tb1,tb2,by = "date")
Num_mutation["Freq"] <- Num_mutation$num1 / Num_mutation$num2
ggplot(data = Num_mutation, mapping = aes(x = date, y = Freq)) +
  geom_point() +
  labs(title = "Mutation rate by date, BA.5.2.1") +
  scale_x_discrete(" ")
```

## Week 10
ZLY formula
```{r}

zly1 <- mean(covid_2$count_N,na.rm=TRUE) / mean(covid_2$count_S,na.rm=TRUE)

## Elders and Youths in BA.2
ba2 <- covid_2[covid_2$pangolin_lineage == c("BA.5.2.1"),]
# delta <- covid_2[covid_2$pangolin_lineage == c("BA.5"),]
delta <- covid_2[covid_2$VarShort == c("VOC Delta GK"),]
beta <- covid_2[covid_2$VarShort == c("VOC Beta GH"),]


elder_ba2 <- ba2[ba2$`Patient age` > 60,]
youth_ba2 <- ba2[ba2$`Patient age` < 40,]
elder_delta <- delta[delta$`Patient age` > 60,]
youth_delta <- delta[delta$`Patient age` < 40,]
elder_beta <- beta[beta$`Patient age` > 60,]
youth_beta <- beta[beta$`Patient age` < 40,]

zly1 <- mean(elder_ba2$count_N,na.rm=TRUE) - mean(elder_beta$count_N,na.rm=TRUE)
zly1 <- zly1/(mean(elder_ba2$count_S,na.rm=TRUE) - mean(elder_beta$count_S,na.rm=TRUE))
zly2 <- mean(youth_ba2$count_N,na.rm=TRUE) - mean(youth_beta$count_N,na.rm=TRUE) 
zly2 <- zly2/(mean(youth_ba2$count_S,na.rm=TRUE) - mean(youth_beta$count_S,na.rm=TRUE))



zly3 <- mean(elder_delta$count_N,na.rm=TRUE) - mean(elder_beta$count_N,na.rm=TRUE)
zly3 <- zly3/(mean(elder_delta$count_S,na.rm=TRUE) - mean(elder_beta$count_S,na.rm=TRUE))
zly4 <- mean(youth_delta$count_N,na.rm=TRUE) - mean(youth_beta$count_N,na.rm=TRUE) 
zly4 <- zly4/(mean(youth_delta$count_S,na.rm=TRUE) - mean(youth_beta$count_S,na.rm=TRUE))
zly1/zly2 ## BA.2
zly3/zly4 ## Delta
```

```{r}
ba2 <- covid_2[covid_2$VarShort == c("VOC Alpha GRY"),]
elder <- ba2[ba2$`Patient age` > 60,]
youth <- ba2[ba2$`Patient age` < 40,]

zly1 <- mean(elder$count_N,na.rm=TRUE) / mean(elder$count_S,na.rm=TRUE)
zly2 <- mean(youth$count_N,na.rm=TRUE) / mean(youth$count_S,na.rm=TRUE)
zly1/zly2
```



## Week 11
N/S on Delta&Omicron
```{r}

# zly1 <- mean(covid_2$count_N,na.rm=TRUE) / mean(covid_2$count_S,na.rm=TRUE)

## Elders and Youths in BA.2
A <- covid_2[covid_2$pangolin_lineage == c("BQ.1.1"),]
# B <- covid_2[covid_2$pangolin_lineage == c("BA.2.1"),]
# c <- covid_2[covid_2$pangolin_lineage == c("BA.2"),]
B <- covid_2[covid_2$VarShort == c("VOC Delta GK"),]
C <- covid_2[covid_2$VarShort == c("VOC Beta GH"),]

zly1 <- mean(A$count_N,na.rm=TRUE) - mean(C$count_N,na.rm=TRUE)
zly1 <- zly1/(mean(A$count_S,na.rm=TRUE) - mean(C$count_S,na.rm=TRUE))
zly2 <- mean(B$count_N,na.rm=TRUE) - mean(C$count_N,na.rm=TRUE)
zly2 <- zly2/(mean(B$count_S,na.rm=TRUE) - mean(C$count_S,na.rm=TRUE))

# zly1 <- mean(A$count_N,na.rm=TRUE) / mean(A$count_S,na.rm=TRUE)
# zly2 <- mean(B$count_N,na.rm=TRUE) / mean(B$count_S,na.rm=TRUE)

zly1 / zly2
```

```{r}

tab <- c(0.3769038,0.2190845,0.1797233,0.2105012,0.2507981,0.1953743,0.199553,0.3048932
)
var <- c("BA.1",	"BA.2",	"BA.2.1",	"BA.4"	,"BA.5"	,"BA.5.2.1","BF.7","BQ.1.1")
tb <- data.frame(var,tab)
tb$var <- factor(tb$var,levels = c("BA.1",	"BA.2",	"BA.2.1",	"BA.4"	,"BA.5"	,"BA.5.2.1","BF.7","BQ.1.1"))
# plot(tb, main = bquote('rdNdS'))
ggplot(tb,mapping = aes(x = tb$var, y = tb$tab)) +
  geom_bar(position="dodge",stat="identity") +
  labs(title = "rdNdS: lineages / Delta") 
# +
#   scale_y_continuous(limits=c(0.75,1.1),oob=rescale_none)
```

```{r}
# 
# E <- covid_2[covid_2$pangolin_lineage == c("BQ.1.1"),]
# E <- covid_2[covid_2$VarShort == c("VOC Delta GK"),]
E <- covid_2[covid_2$VarShort == c("VOC Omicron GRA"),]

num_C_N = mean(C$count_N,na.rm = TRUE)
num_C_S = mean(C$count_S,na.rm = TRUE)

D <- E
D['count_N'] = E['count_N'] - num_C_N
D['count_S'] = E['count_S'] - num_C_S
D['dNdS'] = D$count_N / D$count_S

D$col<- ifelse(D$dNdS >= 0, 1, 0)
D$col<-as.factor(D$col)


ggplot(data = D, mapping = aes(x = date, y = dNdS, fill = D$col, col = D$col)) +
  geom_point() +
  labs(title = "dNdS in Omicron")
# ggplot(data = D, mapping = aes(x = date, y = dNdS ,fill = D$col, col = D$col)) +
#   geom_col(position = "identity",show.legend = FALSE, width = .5) +
#   labs(title = "dNdS in BQ.1.1")
```

Check on Spike and others
```{r}

filename <- file.choose()
covid_2<- readRDS(filename)

```

```{r}

# zly1 <- mean(covid_2$count_N,na.rm=TRUE) / mean(covid_2$count_S,na.rm=TRUE)

## Elders and Youths in BA.2
A <- covid_2[covid_2 == c("BQ.1.1"),]
# B <- covid_2[covid_2$pangolin_lineage == c("BA.2.1"),]
# c <- covid_2[covid_2$pangolin_lineage == c("BA.2"),]
B <- covid_2[covid_2$VarShort == c("VOC Delta GK"),]
C <- covid_2[covid_2$VarShort == c("VOC Beta GH"),]

zly1 <- mean(A$count_N,na.rm=TRUE) - mean(C$count_N,na.rm=TRUE)
zly1 <- zly1/(mean(A$count_S,na.rm=TRUE) - mean(C$count_S,na.rm=TRUE))
zly2 <- mean(B$count_N,na.rm=TRUE) - mean(C$count_N,na.rm=TRUE)
zly2 <- zly2/(mean(B$count_S,na.rm=TRUE) - mean(C$count_S,na.rm=TRUE))

# zly1 <- mean(A$count_N,na.rm=TRUE) / mean(A$count_S,na.rm=TRUE)
# zly2 <- mean(B$count_N,na.rm=TRUE) / mean(B$count_S,na.rm=TRUE)

zly1 / zly2

```

Mutations with time
```{r}
# covid_4 <- covid_2[covid_2$VarShort == c("VOC Omicron GRA", "VOC Alpha GRY", "VOC Delta GK", "VOC Beta GH"),]
covid_4 <- covid_2[covid_2$pangolin_lineage == c("BA.1",	"BA.2",	"BA.2.1",	"BA.4"	,"BA.5"	,"BA.5.2.1","BF.7","BQ.1.1"),]
ggplot(data = covid_4, mapping = aes(x = date, y = count_S, col = covid_4$pangolin_lineage)) +
  # geom_point() +
  xlab('date') +
  ylim(0,20) +
  labs(title = "Mutation rate of different variants") +
  geom_smooth(method = lm)
```


Symptons
```{r}

covid_5 <- covid3[covid3$pangolin_lineage == c("BA.2","BA.2.12.1","BA.4","BA.5","BF.7","BQ.1.1"),]
# covid_5 <- covid3[covid3$VarShort == c("VOC Omicron GRA", "VOC Alpha GRY", "VOC Delta GK", "VOC Beta GH"),]
# covid_5 <- [covid3 == c("BQ.1.1"),]

```


```{r}
covid_5$impact <- factor(covid_5$impact, levels = c("LOW","MODERATE","MODIFIER","HIGH"))
ggplot(data = covid_5,aes(x =impact,fill=pangolin_lineage)) +
  geom_bar(alpha=0.4,position = "identity") +
  labs(title = "Symptoms via Lineages_Omicron")

```

Preportion of different lineages by date
```{r}
group <- covid3 %>%
  count(date, pangolin_lineage) %>%
  drop_na()
group <- group[order(group$date, decreasing = TRUE), ]

group <- group %>%                                      # Top N highest values by group
  arrange(desc(n)) %>% 
  group_by(date) %>%
  slice(1:3)
group <- group[group$date > "2022-09-01",]
```


```{r}
ggplot(data = group, mapping = aes(x = date, y = n, fill = pangolin_lineage)) +
  geom_bar(position = "fill", stat = "identity") +
  scale_y_continuous(labels = scales::percent) +
  labs(title = "%viral lineages among infection") %>%
  scale_x_date(date_breaks = "1 month")
```




