---
title: "Covid_4"
author: "zly"
date: "2022-11-15"
output: html_document
---
```{r}
library(rehh)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(data.table)
library(DBI)
library(RSQLite)
library(scales)
library(data.table)
```

```{r}
filename <- file.choose()
covid_2<- readRDS(filename)
## 少的那个
covid_2 <- covid_2 %>%  filter(grepl(pattern = 'Spike', AASubstitutions))
covid_2 <- covid_2[!is.na(covid_2$date),]
# covid_2 <- df[complete.cases(covid),]
# colnames(covid_2)[names(covid_2) == 'GC-Content'] <- "GCContent"
# saveRDS(covid_2, file = filename)
```


## Week 12
Calculate real dn/ds
```{r}
covid_ns <- covid_2 %>% group_by(pangolin_lineage) %>% arrange(date) %>% mutate(no = row_number(date)) ######### "no" here used to delete 5% data, later will be factor for >1 or not

covid_ns$pangolin_lineage[which(covid_ns$VarShort == "VOC Delta GK")] <- "Delta"


# %>% filter(pangolin_lineage == c("BA.1","BA.2","BA.2.12.1","BA.4","BA.5","BF.7","BQ.1.1"))
covid_ns <- covid_ns[-which(covid_ns$no < 5),]

# covid_2 <- covid_2[order(covid_2$pangolin_lineage,covid_2$date)]

covid_n_1 <- aggregate(covid_ns$count_N, by=list( covid_ns$pangolin_lineage,covid_ns$VarShort,covid_ns$date),mean)

# covid_ns <- data.frame(covid_ns,covid_ns_1)
names(covid_n_1) <- c("pangolin_lineage", "VarShort", "date", "count_N")

covid_n_1 <- covid_n_1[order(covid_n_1$pangolin_lineage,covid_n_1$date),]

# ggplot(covid_n_1, aes(x = date, y = count_N, color = pangolin_lineage)) +
#   geom_point() +
#   labs(title = "Count_N by lineage")

############### N ##############
############### S ##############

covid_s_1 <- aggregate(covid_ns$count_S, by=list(covid_ns$pangolin_lineage,covid_ns$VarShort,covid_ns$date),mean)
# covid_ns <- data.frame(covid_ns,covid_ns_1)
names(covid_s_1) <- c("pangolin_lineage", "VarShort", "date", "count_S")

covid_s_1 <- covid_s_1[order(covid_s_1$pangolin_lineage,covid_s_1$date),]

ggplot(covid_s_1, aes(x = date, y = count_S, color = VarShort)) +
  geom_point() +
  labs(title = "Count_S by lineage")

delta_N <- diff(covid_n_1$count_N)
delta_N <- c(0,delta_N)
covid_n_1$delta_N <- delta_N


delta_S <- diff(covid_s_1$count_S)
delta_S <- c(0,delta_S)
covid_s_1$delta_S <- delta_S

dnds <- data.frame(covid_s_1$date, covid_s_1$pangolin_lineage,delta_N/delta_S)
names(dnds) <- c("date","pangolin_lineage","dnds")


dnds <- dnds[!is.infinite(dnds$dnds),]
dnds <- dnds[!is.na(dnds$dnds),]

# ggplot(dnds, aes(x = date, y = dnds)) +
#   geom_point() +
#   ylim(-100,100) +
#   labs(title = "dNdS")


delta_N <- diff(covid_ns$count_N)
delta_N <- c(0,delta_N)
covid_ns$delta_N <- delta_N


delta_S <- diff(covid_ns$count_S)
delta_S <- c(0,delta_S)
covid_ns$delta_S <- delta_S

covid_ns$dnds <- delta_N/delta_S

covid_ns <- covid_ns[!is.infinite(covid_ns$dnds),]
covid_ns <- covid_ns[!is.na(covid_ns$dnds),]
covid_ns <- covid_ns[!is.na(covid_ns$VarShort),]

# ggplot(covid_ns, aes(x = date, y = dnds, col = pangolin_lineage)) +
#   geom_point()
```

## Week 12

```{r}
############ Linear Regression on N
# lineage_name = c("BA.1","BA.2","BA.2.1","BA.2.75","BA.4","BA.5","BA.5.2.1","BF.7","BQ.1","BQ.1.1","BN.1","XBB")


var_name = c("VOC Omicron GRA", "VOC Delta GK")
# var_name = c("VOC Delta GK")

covid_n_2 <- covid_ns[covid_ns$VarShort == var_name,]

fitted_N =  covid_n_2 %>% group_by(pangolin_lineage) %>% do(model = lm(count_N ~ date, data = .))
# plot(fitted_models$model)
# fitted_N$model

######### Linear Regression on S
covid_s_2 <- covid_ns[covid_ns$VarShort == var_name,]
fitted_S =  covid_s_2 %>% group_by(pangolin_lineage) %>% do(model = lm(count_S ~ date, data = .))
# plot(fitted_models$model)
# fitted_S$model
# fitted_S <- lm(count_S ~ date,covid_s_2, subset = (grp == "pango"))
# fitted_S
```

```{r}
# ggplot(data = covid_n_2, mapping = aes(x = date, y = count_N, col = covid_n_2$pangolin_lineage)) +
#   # geom_point() +
#   xlab('date') +
#   labs(title = "delta_N(slope)") +
#   geom_smooth(method = lm)
# 
# ggplot(data = covid_n_2, mapping = aes(x = date, y = count_N, col = covid_n_2$pangolin_lineage)) +
#   geom_point() +
#   xlab('date') +
#   labs(title = "count_N") +
#   ylim(0,100)
# 
# ggplot(data = covid_s_2, mapping = aes(x = date, y = count_S, col = covid_s_2$pangolin_lineage)) +
#   # geom_point() +
#   xlab('date') +
#   labs(title = "delta_S(slope)") +
#   geom_smooth(method = lm)
# 
# ggplot(data = covid_s_2, mapping = aes(x = date, y = count_S, col = covid_s_2$pangolin_lineage)) +
#   geom_point() +
#   xlab('date') +
#   labs(title = "count_S") +
#   ylim(0,50)
```


For more lineages
```{r}
a <- list()
for (i in 1:nrow(fitted_N)) {
  a[i] <- fitted_N[[2]][[i]][["coefficients"]][2] / fitted_S[[2]][[i]][["coefficients"]][2]
}
# dnds <- data.frame(matrix(nrow=0,ncol=2))
dnds <- data.frame(fitted_N$pangolin_lineage)
names(dnds) <- c("pangolin_lineage")
dnds$dNdS <- a

# dnds <- dnds[!is.infinite(dnds$dNdS),]
dnds <- dnds[!is.na(dnds$dNdS),]


# dnds <- dnds[!is.na(dnds$dNdS),]

dnds[dnds$pangolin_lineage == "BA.2.1",]$dNdS
####### Haven't consider p<0.01



# ggplot(data = dnds, aes(x = pangolin_lineage, y = dNdS)) +
#   geom_bar(stat = 'identity')
```


FOR MULTIPLE LINEAGES
```{r}
lineage_name = c("Delta","BA.1","BA.2","BA.2.12.1","BA.2.75","BA.4","BA.5","BA.5.2.1","BF.7","BQ.1","BQ.1.1","BN.1","XBB")
# covid_specific <- covid_2 %>% filter(pangolin_lineage == lineage_name)
# covid_4 <- dnds[dnds$pangolin_lineage == lineage_name,]
dnds_multiple_dnds <- list()
dnds_multiple_lineage <- list()
for (i in 1:length(lineage_name))
{
  dnds_multiple_dnds[i] <- dnds[dnds$pangolin_lineage == lineage_name[i],]$dNdS
  dnds_multiple_lineage[i] <- dnds[dnds$pangolin_lineage == lineage_name[i],]$pangolin_lineage
}
dnds_multiple <- data.frame(dnds_multiple_lineage,dnds_multiple_dnds)

# dnds_multiple <- data.frame(dnds_multiple_lineage)
# names(dnds_multiple) <- c("pangolin_lineage")
# dnds$dNdS <- dnds_multiple_dnds

dnds_multiple <- cbind(dnds_multiple_lineage,dnds_multiple_dnds)
dnds_multiple <- as.data.frame(dnds_multiple)
names(dnds_multiple) <- c("pangolin_lineage","dNdS")
dnds_multiple$dNdS <- as.numeric(dnds_multiple$dNdS)
dnds_multiple$pangolin_lineage <- as.factor(lineage_name)

dnds_multiple$col<- ifelse(dnds_multiple$dNdS >= 1, 1, 0)
dnds_multiple$col<-as.factor(dnds_multiple$col)
dnds_multiple <- dnds_multiple %>%
  mutate(pangolin_lineage = factor(pangolin_lineage, levels = lineage_name))

ggplot(dnds_multiple, mapping = aes(x = dnds_multiple$pangolin_lineage, y = dnds_multiple$dNdS, col = dnds_multiple$col, fill = dnds_multiple$col, levels = lineage_name)) +
  geom_bar(position="dodge",stat="identity") +
  labs(title = "dNdS_new in different Concern Lineages") +
  ylim(0,5)

# dnds[dnds$pangolin_lineage == "XBB",]$dNdS
```
Distribution of a specific lineage
```{r}
lineage_name = lineage_name
# lineage_name = c("BQ.1")
# covid_specific <- covid_2 %>% filter(pangolin_lineage == lineage_name)

covid_specific <- covid_n_2[covid_n_2$pangolin_lineage == lineage_name,]
covid_specific <- covid_specific[!is.na(covid_specific$delta_N),]

dnds[dnds$pangolin_lineage == lineage_name,]$dNdS


ggplot(data = covid_specific, mapping = aes(x = date, y = count_N, col = covid_specific$pangolin_lineage)) +
  # geom_point() +
  xlab('date') +
  labs(title = "delta_N(slope)") +
  geom_smooth(method = lm)

ggplot(data = covid_specific, mapping = aes(x = date, y = count_N, col = covid_specific$pangolin_lineage)) +
  geom_point() +
  xlab('date') +
  labs(title = "count_N")

ggplot(data = covid_specific, mapping = aes(x = date, y = count_S, col = covid_specific$pangolin_lineage)) +
  # geom_point() +
  xlab('date') +
  labs(title = "delta_S(slope)") +
  geom_smooth(method = lm)

ggplot(data = covid_specific, mapping = aes(x = date, y = count_S, col = covid_specific$pangolin_lineage)) +
  geom_point() +
  xlab('date') +
  labs(title = "count_S")

```


Week 13

Proportion of dnds > 1
```{r}

sum(dnds$dNdS > 1) / nrow(dnds)

```

Boxplot of dnds by different lineages
```{r}

boxplot(covid_specific$count_N~covid_specific$pangolin_lineage,
  ylim = c(20,60),
  ylab = "delta_N",
  main = "delta_N by lineages")
```

t-test on distribution
```{r}
ks.test(covid_specific$delta_N[covid_specific$VarShort == "VOC Omicron GRA"], covid_specific$delta_N[covid_specific$VarShort == "VOC Delta GK"], 
        paired = F) ### T-test on Delta & Omicron
```
```{r}
ks.test(covid_specific$delta_N[covid_specific$pangolin_lineage == "BF.7"], covid_specific$delta_N[covid_specific$pangolin_lineage == "BA.5.2.1"], 
        paired = F)


```

Bootstrapping
Delta and Omicron
```{r}

test.stat1 <- mean(covid_specific$count_N[covid_specific$VarShort == "VOC Omicron GRA"]) -
    mean(covid_specific$count_N[covid_specific$VarShort == "VOC Delta GK"])
test.stat1


covid_specific <- covid_specific[covid_specific$VarShort == c("VOC Omicron GRA","VOC Delta GK"),]
# covid_specific$VarShort[covid_specific$`Patient age` > 40] = "VOC Delta GK 2"



set.seed(114514)
n <- length(covid_specific$VarShort)
n

B <- 1000 # num of bs samples
variable <- covid_specific$count_N

BootstrapSample <- matrix(sample(variable, size = n * B, replace = TRUE),
                          nrow = n, ncol = B)
dim(BootstrapSample)

# Init vectors to stor the TEST-STATS
Boot.test.stat1 <- rep(0,B)
Boot.test.stat2 <- rep(0,B)

for (i in 1:B) {
  Boot.test.stat1[i] <- mean(BootstrapSample[1:n/2,i]) -
                              mean(BootstrapSample[floor(n/2+1):n,i])
  
  Boot.test.stat2[i] <- median(BootstrapSample[1:n/2,i]) -
                              median(BootstrapSample[floor(n/2+1):n,i])
}

round(Boot.test.stat1[1:20],1)
mean(Boot.test.stat1 < test.stat1)

plot(density(Boot.test.stat1),
     xlab = expression(bar(Yc) - bar(Ym)),
     main = "mean t-test on Count_N of Delta & Omicron")
```

Targeting on Delta_S
```{r}
test.stat1 <-   mean(covid_specific$count_S[covid_specific$VarShort == "VOC Omicron GRA"]) -
    mean(covid_specific$count_S[covid_specific$VarShort == "VOC Delta GK"])
test.stat1
covid_specific <- covid_specific[covid_specific$VarShort == c("VOC Omicron GRA","VOC Delta GK"),]

set.seed(114514)
n <- length(covid_specific$VarShort)
n

B <- 1000 # num of bs samples
variable <- covid_specific$count_S

BootstrapSample <- matrix(sample(variable, size = n * B, replace = TRUE),
                          nrow = n, ncol = B)
dim(BootstrapSample)

# Init vectors to stor the TEST-STATS
Boot.test.stat1 <- rep(0,B)
Boot.test.stat2 <- rep(0,B)

for (i in 1:B) {
  Boot.test.stat1[i] <- mean(BootstrapSample[1:n/2,i]) -
                              mean(BootstrapSample[floor(n/2+1):n,i])
  
  Boot.test.stat2[i] <- median(BootstrapSample[1:n/2,i]) -
                              median(BootstrapSample[floor(n/2+1):n,i])
}

round(Boot.test.stat1[1:20],1)
mean(Boot.test.stat1 >= test.stat1)

plot(density(Boot.test.stat1),
     xlab = expression(bar(Yc) - bar(Ym)),
     main = "mean t-test on count_S of Delta & Omicron")
```

dnds on important variants
```{r}
# lineage_name = c("Delta","BA.1","BA.2","BA.2.1","BA.2.75","BA.4","BA.5","BA.5.2.1","BF.7","BQ.1","BQ.1.1","BN.1","XBB")
var_name = c("VOC Alpha GRY","VOC Gamma GR","VOC Delta GK","VOC Omicron GRA")

# var_name = c("VOC Omicron GRA", "VOC Delta GK")
# var_name = c("VOC Delta GK")

covid_n_2 <- covid_ns[covid_ns$VarShort == var_name,]

fitted_N =  covid_n_2 %>% group_by(VarShort) %>% do(model = lm(count_N ~ date, data = .))
# plot(fitted_models$model)
# fitted_N$model

######### Linear Regression on S
covid_s_2 <- covid_ns[covid_ns$VarShort == var_name,]
fitted_S =  covid_s_2 %>% group_by(VarShort) %>% do(model = lm(count_S ~ date, data = .))
# plot(fitted_models$model)
# fitted_S$model
# fitted_S <- lm(count_S ~ date,covid_s_2, subset = (grp == "pango"))
# fitted_S


a <- list()
for (i in 1:nrow(fitted_N)) {
  a[i] <- fitted_N[[2]][[i]][["coefficients"]][2] / fitted_S[[2]][[i]][["coefficients"]][2]
}
# dnds <- data.frame(matrix(nrow=0,ncol=2))
dnds <- data.frame(fitted_N$VarShort)
names(dnds) <- c("VarShort")
dnds$dNdS <- a

# dnds <- dnds[!is.infinite(dnds$dNdS),]
dnds <- dnds[!is.na(dnds$dNdS),]


# dnds <- dnds[!is.na(dnds$dNdS),]

dnds[dnds$VarShort == "VOC Omicron GRA",]$dNdS

# covid_specific <- covid_2 %>% filter(pangolin_lineage == lineage_name)
# covid_4 <- dnds[dnds$pangolin_lineage == lineage_name,]
dnds_multiple_dnds <- list()
dnds_multiple_lineage <- list()
for (i in 1:length(var_name))
{
  dnds_multiple_dnds[i] <- dnds[dnds$VarShort == var_name[i],]$dNdS
  dnds_multiple_lineage[i] <- dnds[dnds$VarShort == var_name[i],]$VarShort
}
dnds_multiple <- data.frame(dnds_multiple_lineage,dnds_multiple_dnds)

# dnds_multiple <- data.frame(dnds_multiple_lineage)
# names(dnds_multiple) <- c("pangolin_lineage")
# dnds$dNdS <- dnds_multiple_dnds

dnds_multiple <- cbind(dnds_multiple_lineage,dnds_multiple_dnds)
dnds_multiple <- as.data.frame(dnds_multiple)
names(dnds_multiple) <- c("VarShort","dNdS")
dnds_multiple$dNdS <- as.numeric(dnds_multiple$dNdS)
dnds_multiple$VarShort <- as.factor(var_name)

dnds_multiple$col<- ifelse(dnds_multiple$dNdS >= 1, 1, 0)
dnds_multiple$col<-as.factor(dnds_multiple$col)
dnds_multiple <- dnds_multiple %>%
  mutate(VarShort = factor(VarShort, levels = var_name))

ggplot(dnds_multiple, mapping = aes(x = dnds_multiple$VarShort, y = dnds_multiple$dNdS, col = dnds_multiple$col, fill = dnds_multiple$col, levels = var_name)) +
  geom_bar(position="dodge",stat="identity") +
  labs(title = "dNdS_new in different Concern Lineages")

# dnds[dnds$VarShort == "XBB",]$dNdS
```

